### ISSUE TITLE
Unsupported SetIncludingPropertiesFromMapItem

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#168]
Hello

I am catch exception:

```
java.lang.UnsupportedOperationException: Unsupported set clause: SetIncludingPropertiesFromMapItem(Variable(n),Parameter(properties,Any))
	at org.opencypher.gremlin.translation.context.WalkerContext.unsupported(WalkerContext.scala:72)
	at org.opencypher.gremlin.translation.walker.SetWalker$$anonfun$walkSetClause$1.apply(SetWalker.scala:66)
	at org.opencypher.gremlin.translation.walker.SetWalker$$anonfun$walkSetClause$1.apply(SetWalker.scala:53)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.opencypher.gremlin.translation.walker.SetWalker.walkSetClause(SetWalker.scala:53)
	at org.opencypher.gremlin.translation.walker.SetWalker.walkClause(SetWalker.scala:42)
	at org.opencypher.gremlin.translation.walker.SetWalker$.walkClause(SetWalker.scala:33)
```

Query like that
```
MATCH (n) WHERE id(n) = {id}
SET n += {properties} 
RETURN n
```

And parameters like that
```
id=40964288, 
properties={key=value, ...}
```

**Comment by dwitry** [comment]
Hello,

can confirm, when using a map to set multiple properties on element, currently it only works with inlined values and not parameters.

Will fix, thanks for reporting.
