### ISSUE TITLE
Translation library does not work due to missing dependencies

### ISSUE THREAD

**Issue by bechbd** [opencypher/cypher-for-gremlin#258]
I have added the translation layer to a new project but whenever I run this it is missing dependencies and I get the following error.  I have attached a sample project demonstrating this error.  Am I doing something wrong or are there some additional dependencies that need to be added?

Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
	at org.parboiled.scala.SuppressSubnodes$.<init>(RuleOption.scala:35)
	at org.parboiled.scala.SuppressSubnodes$.<clinit>(RuleOption.scala)
	at org.parboiled.scala.Parser$class.rule(Parser.scala:76)
	at org.parboiled.scala.Parser$class.rule(Parser.scala:63)
	at org.opencypher.gremlin.translation.preparser.CypherPreParser$.rule(CypherPreParser.scala:21)
	at org.opencypher.v9_0.parser.Base$class.WS(Base.scala:76)
	at org.opencypher.gremlin.translation.preparser.CypherPreParser$.WS(CypherPreParser.scala:21)
	at org.opencypher.gremlin.translation.preparser.CypherPreParser$.QueryWithOptions(CypherPreParser.scala:25)
	at org.opencypher.gremlin.translation.preparser.CypherPreParser$.apply(CypherPreParser.scala:22)
	at org.opencypher.gremlin.translation.CypherAst$.parse(CypherAst.scala:225)
	at org.opencypher.gremlin.translation.CypherAst$.parse(CypherAst.scala:217)
	at org.opencypher.gremlin.translation.CypherAst$.parse(CypherAst.scala:199)
	at org.opencypher.gremlin.translation.CypherAst.parse(CypherAst.scala)
	at org.opencypher.gremlin.translation.TranslationFacade.toGremlinGroovy(TranslationFacade.java:54)
	at org.opencypher.gremlin.translation.TranslationFacade.toGremlinGroovy(TranslationFacade.java:43)
	at App$.main(App.scala:7)
	at App.main(App.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more

[untitled2.zip](https://github.com/opencypher/cypher-for-gremlin/files/3041115/untitled2.zip)

**Comment by dwitry** [comment]
Hello @bechbd,

in provided sample project, you are using Scala 2.12. Cypher for Gremlin 1.0.0 uses Scala 2.11. You either need to use Scala 2.11 with CfoG 1.0.0, or use latest CfoG snapshot which was recently [upgraded](https://github.com/opencypher/cypher-for-gremlin/commit/a83e8b87e0ed629fc0e0ab6c26d26df3f0af96e6) to 2.12 ([build](https://github.com/opencypher/cypher-for-gremlin#development) on your machine or use [JitPack](https://jitpack.io/#opencypher/cypher-for-gremlin/master-SNAPSHOT))

Please confirm if this solves the issue.

**Comment by bechbd** [comment]
Thank you, changing that to Scala 2.11 fixed my issue.
