### ISSUE TITLE
CASE expression failed

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#268]
Sample query

```
MATCH (n:test)
RETURN 
  CASE split(n.name, '_')[0] 
    WHEN split(n.name, '_')[1] THEN toString(n.name + 'a')
    ELSE NULL
  END as r
```

Exception:

```
21:55:11.396 [gremlin-server-worker-1] WARN  o.a.t.g.s.h.OpExecutorHandler - Unsupported value expression: Add(Property(Variable(n),PropertyKeyName(name)),StringLiteral(a))
java.lang.UnsupportedOperationException: Unsupported value expression: Add(Property(Variable(n),PropertyKeyName(name)),StringLiteral(a))
	at org.opencypher.gremlin.translation.context.WalkerContext.unsupported(WalkerContext.scala:69)
	at org.opencypher.gremlin.translation.walker.NodeUtils$.traversalValueToJava(NodeUtils.scala:51)
	at org.opencypher.gremlin.translation.walker.NodeUtils$.expressionValue(NodeUtils.scala:35)
	at org.opencypher.gremlin.translation.walker.NodeUtils$.traversalValueOption(NodeUtils.scala:74)
	at org.opencypher.gremlin.translation.walker.ExpressionWalker.$anonfun$caseExpression$4(ExpressionWalker.scala:612)
```

**Comment by dwitry** [comment]
Resolved by #269
