### ISSUE TITLE
UNWIND with WHERE generate failed gremlin

### ISSUE THREAD

**Issue by mad** [opencypher/cypher-for-gremlin#273]
Sample query

```
UNWIND {data} as data
WITH data
WHERE data.person.name IS NULL
RETURN data
```

Where data is 
```
{
  data: [ 
    { 
      person: { name: "a" }
    }
  ]
}
```
Produce next gremlin
```
g.inject('  cypher.start')
.choose(__.constant([[person: [name: 'a']]]), __.constant([[person: [name: 'a']]]), __.constant('  cypher.null'))
.unfold().as('data')
.project('data').by(__.identity())
.where(__.project('  GENERATED1', '  GENERATED2')
.by(__.select('data'))
.by(__.constant('person'))
.select(values)
.map(cypherContainerIndex())
.is(neq('  cypher.null'))
.hasNot('name'))
.select('data').as('data').project('data')
.by(__.identity())
```

And raise exception when exectuted. I check on TinkerGraph 

```
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to org.apache.tinkerpop.gremlin.structure.Element
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.PropertiesStep.flatMap(PropertiesStep.java:50) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.test(TraversalUtil.java:84) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.NotStep.filter(NotStep.java:46) ~[gremlin-core-3.3.4.jar:3.3.4]
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38) ~[gremlin-core-3.3.4.jar:3.3.4]
```

**Comment by dwitry** [comment]
Hello @mad, 

this is bug indeed, thank you for reporting this.

Fix [pushed](https://github.com/opencypher/cypher-for-gremlin/commit/8425b9c50b55fe27abc7b859a30ebbdc50b36a1b) to `tinkerpop334` as well.
